# Generated by Django 2.2.11 on 2020-03-14 14:06

from django.db import migrations, models
import djongo.models.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('word', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('summaries', djongo.models.json.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('summary_text', models.CharField(max_length=5000)),
            ],
        ),
    ]
